//go:build embed

package static

import (
	"embed"
	"io/fs"

	"github.com/gin-gonic/gin"
)

// The dist tree is generated by scripts/prepare-embed-assets.sh before
// `go build -tags embed`; keeping it package-local satisfies Go embed rules.
//
//go:embed dist/admin
var adminDist embed.FS

//go:embed dist/user
var userDist embed.FS

//go:embed dist/docs
var docsDist embed.FS

func RegisterEmbedded(r *gin.Engine) error {
	adminFS, err := fs.Sub(adminDist, "dist/admin")
	if err != nil {
		return err
	}
	userFS, err := fs.Sub(userDist, "dist/user")
	if err != nil {
		return err
	}
	docsFS, err := fs.Sub(docsDist, "dist/docs")
	if err != nil {
		return err
	}
	return RegisterSites(r, []Site{
		{Prefix: "/admin", FS: adminFS, Index: "index.html", Mode: ModeSPA},
		{Prefix: "/user", FS: userFS, Index: "index.html", Mode: ModeSPA},
		{Prefix: "/docs", FS: docsFS, Index: "index.html", Mode: ModeDocs},
	})
}
