CREATE TABLE IF NOT EXISTS request_logs (
    id                    BIGINT       NOT NULL,
    created_at            DATETIME(3)  NOT NULL,
    user_id               BIGINT       NOT NULL,
    token_id              BIGINT       NOT NULL,
    dept_id               BIGINT,
    group_id              BIGINT,
    event_type            TINYINT      NOT NULL DEFAULT 0,
    client_model          VARCHAR(128) NOT NULL,
    upstream_model        VARCHAR(128) NOT NULL DEFAULT '',
    channel_id            BIGINT,
    protocol              VARCHAR(16)  NOT NULL DEFAULT 'openai',
    endpoint              VARCHAR(64)  NOT NULL,
    ip                    VARCHAR(45)  NOT NULL DEFAULT '',
    user_agent            VARCHAR(256) NOT NULL DEFAULT '',
    status_code           SMALLINT     NOT NULL DEFAULT 0,
    latency_ms            INT          NOT NULL DEFAULT 0,
    ttft_ms               INT          NOT NULL DEFAULT 0,
    stream                TINYINT(1)   NOT NULL DEFAULT 0,
    input_tokens          INT          NOT NULL DEFAULT 0,
    output_tokens         INT          NOT NULL DEFAULT 0,
    cached_tokens         INT          NOT NULL DEFAULT 0,
    reasoning_tokens      INT          NOT NULL DEFAULT 0,
    total_quota           BIGINT       NOT NULL DEFAULT 0,
    billing_input_ratio   DECIMAL(10,4) NOT NULL DEFAULT 0,
    billing_output_ratio  DECIMAL(10,4) NOT NULL DEFAULT 0,
    billing_group_ratio   DECIMAL(10,4) NOT NULL DEFAULT 1,
    error_code            INT          NOT NULL DEFAULT 0,
    error_msg             VARCHAR(512) NOT NULL DEFAULT '',
    trace_id              VARCHAR(64)  NOT NULL DEFAULT '',
    PRIMARY KEY (id, created_at),
    KEY idx_req_user_time        (user_id, created_at),
    KEY idx_req_token_time       (token_id, created_at),
    KEY idx_req_channel_time     (channel_id, created_at),
    KEY idx_req_clientmodel_time (client_model, created_at),
    KEY idx_req_event_time       (event_type, created_at)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
PARTITION BY RANGE (TO_DAYS(created_at)) (
    PARTITION p_min     VALUES LESS THAN (TO_DAYS('2026-01-01')),
    PARTITION p_2026_05 VALUES LESS THAN (TO_DAYS('2026-06-01')),
    PARTITION p_max     VALUES LESS THAN MAXVALUE
);
