CREATE TABLE IF NOT EXISTS api_tokens (
    id              BIGINT       NOT NULL,
    user_id         BIGINT       NOT NULL,
    name            VARCHAR(64)  NOT NULL DEFAULT '',
    key_hash        VARCHAR(64)  NOT NULL,
    key_prefix      VARCHAR(32)  NOT NULL,
    quota_limit     BIGINT       NULL,
    quota_used      BIGINT       NOT NULL DEFAULT 0,
    allowed_models  JSON         NOT NULL,
    allowed_ips     JSON         NOT NULL,
    rpm_limit       INT          NOT NULL DEFAULT 0,
    tpm_limit       INT          NOT NULL DEFAULT 0,
    expires_at      DATETIME(3)  NULL,
    last_used_at    DATETIME(3)  NULL,
    status          TINYINT      NOT NULL DEFAULT 0,
    created_at      DATETIME(3)  NOT NULL,
    updated_at      DATETIME(3)  NOT NULL,
    deleted_at      DATETIME(3)  NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_api_tokens_key_hash (key_hash),
    KEY idx_api_tokens_user_status (user_id, status),
    KEY idx_api_tokens_expires (expires_at),
    KEY idx_api_tokens_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
