CREATE TABLE IF NOT EXISTS accounts (
    id                       BIGINT       NOT NULL PRIMARY KEY,
    channel_id               BIGINT       NOT NULL,
    share_tag                VARCHAR(64)  NULL,
    name                     VARCHAR(128) NOT NULL DEFAULT '',
    provider                 VARCHAR(32)  NOT NULL,
    tier                     VARCHAR(32)  NOT NULL DEFAULT 'unknown',
    cred_type                VARCHAR(16)  NOT NULL,
    email                    VARCHAR(128) NULL,
    external_account_id      VARCHAR(64)  NULL,
    credentials              TEXT         NOT NULL,
    priority                 SMALLINT     NOT NULL DEFAULT 0,
    weight                   INT          NOT NULL DEFAULT 100,
    status                   TINYINT      NOT NULL DEFAULT 0,
    cooldown_until           DATETIME(3)  NULL,
    last_failure_at          DATETIME(3)  NULL,
    last_failure_reason      VARCHAR(256) NOT NULL DEFAULT '',
    consec_failures          INT          NOT NULL DEFAULT 0,
    last_success_at          DATETIME(3)  NULL,
    last_used_at             DATETIME(3)  NULL,
    quota_5h_total           BIGINT       NULL,
    quota_5h_remaining       BIGINT       NULL,
    quota_5h_reset_at        DATETIME(3)  NULL,
    quota_week_total         BIGINT       NULL,
    quota_week_remaining     BIGINT       NULL,
    quota_week_reset_at      DATETIME(3)  NULL,
    quota_synced_at          DATETIME(3)  NULL,
    access_token_expires_at  DATETIME(3)  NULL,
    refresh_token_valid      TINYINT      NOT NULL DEFAULT 0,
    last_refreshed_at        DATETIME(3)  NULL,
    import_source            VARCHAR(32)  NOT NULL DEFAULT '',
    extra                    JSON         NULL,
    created_at               DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at               DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at               DATETIME(3)  NULL,
    INDEX idx_accounts_channel_status (channel_id, status),
    INDEX idx_accounts_share_status (share_tag, status),
    INDEX idx_accounts_status_cooldown (status, cooldown_until),
    INDEX idx_accounts_provider_tier (provider, tier),
    INDEX idx_accounts_token_exp (access_token_expires_at, status),
    INDEX idx_accounts_deleted (deleted_at),
    UNIQUE KEY uk_accounts_provider_extid (provider, external_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
