ALTER TABLE channels ADD COLUMN IF NOT EXISTS pool_enabled SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS account_strategy VARCHAR(16) NOT NULL DEFAULT 'top_k';
ALTER TABLE channels ADD COLUMN IF NOT EXISTS account_top_k SMALLINT NOT NULL DEFAULT 3;
